### ISSUE TITLE
Add download option for SVG

### ISSUE THREAD

**Issue by fdagner** [TRMSC/imagescene-generator#8]
It would be great if the result could be downloaded as an SVG file.

**Comment by TRMSC** [comment]
Thanks for your request @fdagner! This great idea will be implemented! 😊

**Comment by TRMSC** [comment]
Successfully closed with c7f14fcd84e73101b95c95c8cd84cf0181d0ebfd and 2bebc7d18dc1a6738d561170e7ea18ce7182ef26 😊
