### ISSUE TITLE
Revise reference to templates

### ISSUE THREAD

**Issue by fdagner** [TRMSC/imagescene-generator#9]
https://github.com/TRMSC/imagescene-generator/blob/6f33080401dbe554fb71d261b77cb64cca5062df/docs/src/script.js#L277C125-L277C125

It is difficult to make a pull request for a template if the templates are referenced with a hard link. This means that you cannot test a template in a fork.

**Comment by fdagner** [comment]
Maybe this is covered in #5?

**Comment by TRMSC** [comment]
Thank you for your thoughts and for mentioning this point. 😊
I'm not happy with the hardlink either but I used this way for getting the plaintext of the file...
It should still be possible to build this kind of link with a relative relation and I will do this in #5 like you have suggested! 👍

**Comment by TRMSC** [comment]
The new progress  worked only by trying on the server and didn't work for github pages... The older workflow was retrieved in 364728c8ed8595403292429fe235c3fed7fc96e8 temporary until a new solution is found...

**Comment by TRMSC** [comment]
There was still a bug that should be solved now with bc03b9329e973979b1b02e7dc177e23b00615031
